# 3. Bonus

Για το μπόνους ερώτημα χρησιμοποιώ κάποια stopwords για να καθαρίσω κάπως το αρχείο από περιττές λέξεις
και να βοηθήσω στη καλύτερη εκτέλεση των αλγόριθμων. Θα δημιουργήσω και χρησιμοποιήσω ένα καινούριο αρχείο 
που θα το ονομάσω updated_data.tsv το οποίο θα έχει καθαριστεί από περισσιο υλικό. Μία ιδέα που δε πρόλαβα να 
υλοποιήσω ήταν να ενώσω το τίτλο και το περιεχόμενο των άρθρων το όποιο ενδεχομένως να βελτίωνε ακόμα περισσότερο 
την απόδοση των αλγόριθμων.

In [1]:
import csv
import numpy as np
import os, glob
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import preprocessing
from string import punctuation
import matplotlib.pyplot as plt
import string
import nltk
from nltk.corpus import stopwords


my_stopwords = set(stopwords.words('english'))
other_words = {'said','say','says','just','did','was','were','year','years','like','people','tell','tells'
               'told','report','reported','get','also','however','already','may','almost','hes','ask','would',
              'could','one'}
my_stopwords = my_stopwords.union(other_words)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)

In [2]:
#ka8arizei ena text sumvola, an einai adeio to kanei null
def clean_string(text): # ta kanei null
    text = ''.join([word for word in text if word not in string.punctuation])
    text = text.lower()
    text = ' '.join([word for word in text.split() if word not in my_stopwords])
    if text == '': 
        text = 'NULL' 
    return text

In [3]:
data = pd.read_csv('data.tsv',sep="\t",encoding='utf-8')
updated_data = pd.DataFrame(data)
updated_data

,id,title,content,category
0,1,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarner...,business
1,1,Ad sales boost Time Warner profit,"The firm, which is now one of the biggest inve...",business
2,1,Ad sales boost Time Warner profit,Time Warner said on Friday that it now owns 8%...,business
3,1,Ad sales boost Time Warner profit,Time Warner's fourth quarter profits were slig...,business
4,1,Ad sales boost Time Warner profit,TimeWarner is to restate its accounts as part ...,business
...,...,...,...,...
10662,4401,Losing yourself in online gaming,I bought the US version of World of Warcraft w...,tech
10663,4401,Losing yourself in online gaming,Having played MMORPG games for some years I ag...,tech
10664,4401,Losing yourself in online gaming,Unless there is undeniable medical proof that ...,tech
10665,4401,Losing yourself in online gaming,These people are pathetic. They need to get of...,tech
10666,4401,Losing yourself in online gaming,"24hours, when i was a kid at school and i was ...",tech

In [4]:
#remove punctuation and stopwords 
for i in range(0,len(updated_data['content'])):
    temp = clean_string(updated_data['content'][i])
    updated_data['content'].replace(to_replace=updated_data['content'][i],value=temp,inplace=True)

updated_data.to_csv('updated_data.tsv' ,sep='\t', quoting=csv.QUOTE_NONE ,index=False)